Update .gitlab-ci.yml file [skip ci]

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -132,63 +132,69 @@ deploy-php:
     - kubectl wait --for=condition=available deployment/php-matomo -n ${NAMESPACE} --timeout=1m
     - kubectl apply -f manifests/backend/3-php-svc.yaml
       
-# validate-php-deployment:
-#   stage: validate-php 
-#   needs:
-#     - deploy-php
-#   script:
-#     - kubectl rollout status deployment/php-matomo --timeout=5s 
+validate-php-deployment:
+  <<: *env-vars 
+  stage: validate-php 
+  needs:
+    - deploy-php
+  script:
+    - kubectl -n ${NAMESPACE} rollout status deployment/php-matomo --timeout=5s 
 
-# validate-php-service:
-#   stage: validate-php 
-#   needs:
-#     - validate-php-deployment
-#   script:
-#     - kubectl config set-context --namespace matomo --current      
-#     - |
-#       if kubectl run php-test-${CI_JOB_ID} --image=alpine -it --rm --restart=Never -- \
-#       sh -c apk update --no-check-certificate && apk add --no-cache fcgi --no-check-certificate && \
-#       cgi-fcgi -bind -connect php-matomo:9000;then 
-#       echo "PHP backend connection OK"
-#       fi 
-#       exit 0
-#       echo "PHP backend connection fail"
-#       exit 1
+validate-php-service:
+  <<: *env-vars 
+  stage: validate-php 
+  needs:
+    - validate-php-deployment
+  script:
+    - kubectl config set-context --namespace ${NAMESPACE} --current      
+    - |
+      if kubectl run php-test-${CI_JOB_ID} --image=alpine -it --rm --restart=Never -- \
+      sh -c apk update --no-check-certificate && apk add --no-cache fcgi --no-check-certificate && \
+      cgi-fcgi -bind -connect php-matomo:9000;then 
+      echo "PHP backend connection OK"
+      fi 
+      exit 0
+      echo "PHP backend connection fail"
+      exit 1
 
-# validate-nginx-conf:
-#   stage: validate-nginx 
-#   script:
-#     - kubectl apply -f manifests/frontend/ --dry-run=client 
+validate-nginx-conf:
+  stage: validate-nginx 
+  script:
+    - kubectl apply -f manifests/frontend/ --dry-run=client 
   
-# deploy-nginx:
-#   stage: validate-nginx 
-#   needs: 
-#     - validate-nginx-conf
-#   script:
-#     - kubectl apply -f manifests/frontend/0-nginx-cm.yaml 
-#     - kubectl apply -f manifests/frontend/1-nginx-deploy.yaml 
-#     - kubectl -n matomo wait --for=condition=available deployment/nginx-matomo --timeout=1m
-#     - kubectl apply -f manifests/frontend/2-nginx-service.yaml 
+deploy-nginx:
+  stage: validate-nginx 
+  needs: 
+    - validate-nginx-conf
+    - deploy-db 
+  dependencies:
+    - deploy-db 
+  script:
+    - kubectl apply -f manifests/frontend/0-nginx-cm.yaml 
+    - kubectl apply -f manifests/frontend/1-nginx-deploy.yaml 
+    - kubectl -n matomo wait --for=condition=available deployment/nginx-matomo --timeout=1m
+    - kubectl apply -f manifests/frontend/2-nginx-service.yaml 
 
-# validate-nginx-service:
-#   stage: validate-nginx 
-#   needs: 
-#     - deploy-nginx 
-#   script:
-#     - kubectl config set-context --namespace matomo --current
-#     - kubectl -n matomo wait --for=condition=available deployment/nginx-matomo --timeout=1m
-#     - |
-#       if kubectl run frontent-test-${CI_JOB_ID} --image=curlimages/curl -i --rm --restart=Never -- \
-#       curl -s --fail -o /dev/null http://nginx-matomo/;then 
-#       echo 'Nginx connection OK'
-#       exit 0
-#       fi
-#       exit 1
+validate-nginx-service:
+  <<: *env-vars 
+  stage: validate-nginx 
+  needs: 
+    - deploy-nginx 
+  script:
+    - kubectl config set-context --namespace ${NAMESPACE} --current
+    - sleep 5
+    - |
+      if kubectl run frontent-test-${CI_JOB_ID} --image=curlimages/curl -i --rm --restart=Never -- \
+      curl -s --fail -o /dev/null http://nginx-matomo/;then 
+      echo 'Nginx connection OK'
+      exit 0
+      fi
+      exit 1
 
-# validate-ingress-conf:
-#   stage: validate-ingress
-#   script: 
-#     - kubectl apply -f manifests/ingress/matomo.yaml --dry-run=client 
+validate-ingress-conf:
+  stage: validate-ingress
+  script: 
+    - kubectl apply -f manifests/ingress/matomo.yaml --dry-run=client 
 
 # deploy-ingress:
 #   stage: validate-ingress
